### ISSUE TITLE
Feature request: LWT - publish to mqtt when desk is disconnected or can't connect

### ISSUE THREAD

**Issue by adidoes** [alex20465/deskbluez#3]
Hello,

Thank you for the awesome project, saved me a lot of hours :)

I have a small request, is it possible to send a message to a mqtt topic when the desk gets disconnected or it can't reconnect automatically?

Thanks!

**Comment by alex20465** [comment]
It reconnects automatically, since we publish also the manual-position changes. Although the current implemented method is not reliable, I will need to educate my-self into how to keep low-energy-bluetooth devices connected permanently.

I use the current re-connection method but sometimes it doesn't work and I have to restart the process.

I will take a look how to implement a reliable solution but I would appreciate some help. Thanks.

**Comment by darkkatarsis** [comment]
I have exactly the same problem, after a few hours of work it just stops working. I need to repeat the process

**Comment by maxime1992** [comment]
@adidoes I see you mentioned mqtt, is it by any chance because you were trying to build an addon for home assistant :upside_down_face:? I'd very appreciate to hear from you if that's the case, could save me a lot of time!

**Comment by adidoes** [comment]
@maxime1992 I was using it with node-red, unfortunately it kept dropping the connection so I had to move to something else, now I just use Desk Remote Control on the mac
